build_from:
  armv7: ghcr.io/home-assistant/armv7-base-debian:trixie
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:trixie
  amd64: ghcr.io/home-assistant/amd64-base-debian:trixie
  i386: ghcr.io/home-assistant/i386-base-debian:trixie
