name: Check addon with linters
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
 workflows:
    uses: Poeschl-HomeAssistant-Addons/workflows/.github/workflows/addon-pr.yaml@main