name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published

jobs:
  workflows:
    uses: Poeschl-HomeAssistant-Addons/workflows/.github/workflows/addon-deploy.yaml@main
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
